import {lessons} from '../data/learning';
const key='vibe-guide-learning-v1';
type State={version:1;idea:string;later:string;completed:string[];current:string};
export function parseLearning(raw:string|null):State {if(!raw)return {version:1,idea:'',later:'',completed:[],current:'idea'};const s=JSON.parse(raw);if(s.version!==1||typeof s.idea!=='string'||typeof s.later!=='string'||!Array.isArray(s.completed)||!s.completed.every((x:unknown)=>typeof x==='string')||typeof s.current!=='string')throw new Error('Invalid saved draft');return {...s,completed:s.completed.filter((id:string)=>lessons.some(l=>l.id===id)),current:lessons.some(l=>l.id===s.current)?s.current:'idea'};}
export function initLearning(){const root=document.querySelector<HTMLElement>('[data-learning]');if(!root)return;const en=root.dataset.locale==='en';const status=root.querySelector<HTMLElement>('[data-learning-status]')!;let state:State;let writable=true;try{state=parseLearning(localStorage.getItem(key));}catch{state=parseLearning(null);writable=false;status.textContent=en?'Saved data could not be read. It has not been overwritten. Download new notes before leaving.':'无法读取已保存的资料，原内容未覆盖。离开前请下载本次草稿。';}
const save=()=>{if(!writable)return false;try{localStorage.setItem(key,JSON.stringify(state));status.textContent=en?'Saved in this browser.':'已保存到当前浏览器。';return true;}catch{status.textContent=en?'Saving failed. Download the draft before leaving.':'保存失败，离开前请下载草稿。';return false;}};
const current=root.dataset.lesson;if(current){state.current=current;if(writable)save();}
const idea=root.querySelector<HTMLTextAreaElement>('[name=idea]');const later=root.querySelector<HTMLTextAreaElement>('[name=later]');if(idea)idea.value=state.idea;if(later)later.value=state.later;
root.querySelector('[data-draft-form]')?.addEventListener('input',()=>{state.idea=idea!.value;state.later=later!.value;save();});
root.querySelector('[data-example]')?.addEventListener('click',()=>{if(idea!.value.trim()){status.textContent=en?'The existing idea was kept. Clear it first to use the example.':'已有想法已保留。需要示例时，先清空想法框。';return;}idea!.value=en?'A personal learning journal: write, save, and find notes in the same browser. No accounts or sync in version one.':'给自己用的学习记录：填写、保存，在同一浏览器里再次看到。第一版不做登录和同步。';state.idea=idea!.value;save();});
root.querySelector('[data-export]')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='vibe-guide-draft.json';document.body.append(a);a.click();a.remove();const fallback=root.querySelector<HTMLElement>('[data-export-fallback]')!;fallback.hidden=false;(fallback.querySelector('textarea') as HTMLTextAreaElement).value=JSON.stringify(state,null,2);status.textContent=en?'Download requested. If nothing appears, expand the backup below and copy it.':'已请求下载。如未出现文件，可展开下方备份并复制留底。';setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
root.querySelectorAll<HTMLElement>('[data-complete],[data-finish]').forEach(el=>el.addEventListener('click',()=>{const id=el.dataset.complete??el.dataset.finish!;if(!state.completed.includes(id))state.completed.push(id);save();}));
root.querySelectorAll<HTMLElement>('[data-progress]').forEach(el=>{if(state.completed.includes(el.dataset.progress!)){el.textContent=en?'Checked ✓':'已核对 ✓';}});
const code=root.querySelector<HTMLElement>('[data-template-text]');if(code&&state.idea)code.textContent=(en?'My project idea: ':'我的项目想法：')+state.idea+'\n'+(en?'Later / undecided: ':'以后再做 / 未确定：')+(state.later||(en?'Undecided':'尚未确定'))+'\n\n'+code.textContent;
}
