import {readConfirmed,exportProject,projectStorage as localStorage} from './project-storage.ts';
import {ideaTemplate as ideaTemplates,ideaExample} from '../data/idea-template';
import {lessons} from '../data/learning';
const key='vibe-guide-learning-v1';
type State={version:1;idea:string;later:string;completed:string[];current:string;ideaConfirmed?:string;lastViewed?:string;checks?:Record<string,{verdict:string;version:string;date:string;note:string}>};
export function parseLearning(raw:string|null):State {if(!raw)return {version:1,idea:'',later:'',completed:[],current:'idea'};const s=JSON.parse(raw);if(s.version!==1||typeof s.idea!=='string'||typeof s.later!=='string'||!Array.isArray(s.completed)||!s.completed.every((x:unknown)=>typeof x==='string')||typeof s.current!=='string')throw new Error('Invalid saved draft');if(s.ideaConfirmed!==undefined&&typeof s.ideaConfirmed!=='string')throw Error('Invalid confirmed idea');if(s.checks!==undefined&&(!s.checks||typeof s.checks!=='object'||Object.values(s.checks).some((c:any)=>!c||typeof c.version!=='string'||typeof c.date!=='string'||typeof c.note!=='string'||!['passed','failed','not-tested','not-applicable'].includes(c.verdict))))throw Error('Invalid check record');return {...s,completed:s.completed.filter((id:string)=>lessons.some(l=>l.id===id)),current:s.current==='goal'?'description':lessons.some(l=>l.id===s.current)?s.current:'idea'};}
export function initLearning(){const root=document.querySelector<HTMLElement>('[data-learning]');if(!root)return;const en=root.dataset.locale==='en';const status=root.querySelector<HTMLElement>('[data-learning-status]')!;let state:State;let writable=true;try{state=parseLearning(localStorage.getItem(key));}catch{state=parseLearning(null);writable=false;status.textContent=en?'Saved data could not be read. It has not been overwritten. Download new notes before leaving.':'无法读取已保存的资料，原内容未覆盖。离开前请下载本次草稿。';}
const save=()=>{if(!writable)return false;try{localStorage.setItem(key,JSON.stringify(state));status.textContent=en?'Saved in this browser.':'已保存到当前浏览器。';return true;}catch{status.textContent=en?'Saving failed. Download the draft before leaving.':'保存失败，离开前请下载草稿。';return false;}};
const current=root.dataset.lesson;if(current){state.lastViewed=current;if(writable)save();}
const idea=root.querySelector<HTMLTextAreaElement>('[name=idea]');const later=root.querySelector<HTMLTextAreaElement>('[name=later]');const ideaTemplate=ideaTemplates[en?1:0];if(idea)idea.value=state.idea||ideaTemplate;if(later)later.value=state.later;
const result=root.querySelector<HTMLElement>('[data-idea-result]');const personal=root.querySelector<HTMLTextAreaElement>('#idea-personal');const copyIdea=root.querySelector<HTMLButtonElement>('[data-copy-idea]');const ideaStatus=root.querySelector<HTMLElement>('[data-idea-status]');const invalidateIdea=()=>{if(result)result.hidden=true;if(copyIdea)copyIdea.disabled=true;if(ideaStatus)ideaStatus.textContent=en?'Draft changed. Confirm to prepare the new version.':'草稿已修改，请确认生成新版本。';};
root.querySelector('[data-draft-form]')?.addEventListener('input',()=>{invalidateIdea();state.idea=idea!.value;state.later=later!.value;save();});
root.querySelector('[data-example]')?.addEventListener('click',()=>{if(idea!.value.trim()&&idea!.value!==ideaTemplate){status.textContent=en?'The existing idea was kept. Clear it first to use the example.':'已有想法已保留。需要示例时，先清空想法框。';return;}idea!.value=ideaExample[en?1:0];state.idea=idea!.value;invalidateIdea();save();});
root.querySelector('[data-confirm-idea]')?.addEventListener('click',()=>{if(!idea!.value.trim()||(ideaTemplate.match(/【[^】]*】|\[[^\]]*\]/g)||[]).some(placeholder=>idea!.value.includes(placeholder))){ideaStatus!.textContent=en?'Replace every bracketed field, or write undecided.':'请把模板括号里的提示替换成实际内容，或填写“尚未确定”。';idea!.focus();return;}state.idea=idea!.value.trim();state.ideaConfirmed=state.idea;state.later=later!.value;save();personal!.value=state.idea+(state.later?'\n\n'+(en?'Later / undecided: ':'补充想法：')+state.later:'');result!.hidden=false;copyIdea!.disabled=false;ideaStatus!.textContent=en?'Personal draft ready. Review and copy it.':'专属草稿已生成，核对后可一键复制。';});
copyIdea?.addEventListener('click',async()=>{if(copyIdea.disabled)return;let timeout:ReturnType<typeof setTimeout>|undefined;try{await Promise.race([navigator.clipboard.writeText(personal!.value),new Promise((_,reject)=>{timeout=setTimeout(()=>reject(Error()),1800);})]);ideaStatus!.textContent=en?'Copied.':'已复制。';}catch{personal!.focus();personal!.select();ideaStatus!.textContent=en?'Text selected. Press Ctrl+C / ⌘C.':'已选中文字，请按 Ctrl+C / ⌘C 复制。';}finally{if(timeout)clearTimeout(timeout);}});
root.querySelector('[data-export]')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(exportProject(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='vibe-guide-draft.json';document.body.append(a);a.click();a.remove();const fallback=root.querySelector<HTMLElement>('[data-export-fallback]')!;fallback.hidden=false;(fallback.querySelector('textarea') as HTMLTextAreaElement).value=JSON.stringify(exportProject(),null,2);status.textContent=en?'Download requested. If nothing appears, expand the backup below and copy it.':'已请求下载。如未出现文件，可展开下方备份并复制留底。';setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
let checkDirty=false;const checkPanel=root.querySelector<HTMLElement>('[data-personal-check]');
if(checkPanel&&current){const version=checkPanel.querySelector<HTMLInputElement>('[data-check-version]')!;const verdict=checkPanel.querySelector<HTMLSelectElement>('[data-check-verdict]')!;const note=checkPanel.querySelector<HTMLTextAreaElement>('[data-check-note]')!;const message=checkPanel.querySelector<HTMLElement>('[data-check-status]')!;const old=state.checks?.[current];if(old){version.value=old.version;verdict.value=old.verdict;note.value=old.note??'';message.textContent=(en?'Saved at: ':'记录时间：')+old.date;}
 checkPanel.addEventListener('input',()=>{checkDirty=true;message.textContent=en?'Check changed. Save it before marking complete.':'核对内容已修改，请保存后再标记完成。';});
 checkPanel.querySelector('[data-import-check]')?.addEventListener('click',()=>{const record=readConfirmed('learn-accept');if(!record){message.textContent=en?'Confirm the trial record first.':'先确认上方试用记录。';return;}const get=(pattern:RegExp)=>record.split('\n').find(line=>pattern.test(line))?.replace(/^[^:：]+[:：]\s*/,'')??'';checkDirty=true;version.value=get(/^(本次试用版本与入口|Version and entry)[:：]/);note.value=get(/^(实际结果|Actual result)[:：]/);const result=get(/^(结论|Verdict)[:：]/);verdict.value=/^(通过|passed)$/i.test(result)?'passed':/^(失败|failed)$/i.test(result)?'failed':'not-tested';message.textContent=en?'Imported. Review and save the check.':'已带入，请核对后保存本次检查。';});
 checkPanel.querySelector('[data-save-check]')!.addEventListener('click',()=>{if(!version.value.trim()||!note.value.trim()){message.textContent=en?'Add the actual revision and result/reason.':'请填写实际版本和结果/原因。';return;}checkDirty=false;state.checks??={};state.checks[current]={version:version.value.trim(),verdict:verdict.value,note:note.value.trim(),date:new Date().toISOString()};if(!['passed','not-applicable'].includes(verdict.value))state.completed=state.completed.filter(id=>id!==current);save();message.textContent=en?'Saved. Changed projects need a new check.':'已保存；项目改变后需要重新核对。';});
}
root.querySelectorAll<HTMLElement>('[data-complete],[data-finish]').forEach(el=>el.addEventListener('click',(event)=>{const id=el.dataset.complete??el.dataset.finish!;if(checkPanel&&(checkDirty||!['passed',...(['interface','save','test'].includes(id)?['not-applicable']:[])].includes(state.checks?.[id]?.verdict??''))){event.preventDefault();(checkPanel as HTMLDetailsElement).open=true;checkPanel.scrollIntoView({behavior:'smooth',block:'center'});checkPanel.querySelector('[data-check-status]')!.textContent=en?'Record the actual check before marking complete. Untested or failed work stays open.':'请先记录实际核对结论；失败或未测试不能标记完成。';return;}if(!state.completed.includes(id))state.completed.push(id);state.current=lessons.find(l=>!state.completed.includes(l.id)&&l.id!=='publish')?.id??'maintain';save();}));
root.querySelectorAll<HTMLElement>('[data-progress]').forEach(el=>{if(state.completed.includes(el.dataset.progress!)){el.textContent=en?'Checked ✓':'已核对 ✓';}});
}
