export type Crumb={path:string;title:string};
export function safePath(path:unknown):path is string{return typeof path==='string'&&/^\/(zh-cn|en)\//.test(path)&&path.length<1800&&!/[\\\r\n]/.test(path);}
export function readTrail(raw:string|null):Crumb[]{try{const parsed=JSON.parse(raw||'[]');if(!Array.isArray(parsed))return [];return parsed.filter(c=>c&&safePath(c.path)&&typeof c.title==='string').slice(-8).map(c=>({path:c.path,title:c.title.slice(0,90)}));}catch{return [];}}
export function cleanPath(input:URL){const u=new URL(input);u.searchParams.delete('via');return u.pathname+u.search+u.hash;}
export function withTrail(path:string,trail:Crumb[],origin:string){const u=new URL(path,origin);u.searchParams.delete('via');if(trail.length)u.searchParams.set('via',JSON.stringify(trail.slice(-8)));return u.pathname+u.search+u.hash;}
export function initNavigation(){const viewKey='vibe-view:'+cleanPath(new URL(location.href));const saveView=()=>{try{sessionStorage.setItem(viewKey,JSON.stringify({y:scrollY,open:Array.from(document.querySelectorAll('main details')).flatMap((d,i)=>(d as HTMLDetailsElement).open?[i]:[])}));}catch{}};addEventListener('pagehide',saveView);try{const view=JSON.parse(sessionStorage.getItem(viewKey)||'null');if(view&&Array.isArray(view.open)){const details=document.querySelectorAll<HTMLDetailsElement>('main details');view.open.forEach((i:unknown)=>{if(typeof i==='number'&&Number.isInteger(i)&&details[i])details[i].open=true;});if(typeof view.y==='number'&&Number.isFinite(view.y)&&view.y>=0)requestAnimationFrame(()=>scrollTo(0,view.y));}}catch{}const current=new URL(location.href);const trail=readTrail(current.searchParams.get('via'));const back=document.querySelector<HTMLAnchorElement>('[data-entry-back]');const last=trail.at(-1);if(back&&last){back.href=withTrail(last.path,trail.slice(0,-1),location.origin);back.textContent=(document.documentElement.lang==='en'?'← Back to ':'← 返回：')+last.title;}
// URLs carry the route in this tab: reloads, direct links and multiple tabs do not share mutable history.
document.addEventListener('click',event=>{const a=(event.target as Element).closest<HTMLAnchorElement>('a[href]');if(!a||a.hasAttribute('download')||a.matches('[data-entry-back]'))return;saveView();const destination=new URL(a.href,location.href);if(destination.origin!==location.origin||!safePath(destination.pathname))return;if(destination.pathname===location.pathname&&destination.hash)return;if(a.closest('.languages')){const lang=destination.pathname.split('/')[1];a.href=withTrail(cleanPath(destination),trail.map(c=>({...c,path:c.path.replace(/^\/(zh-cn|en)\//,`/${lang}/`)})),location.origin);return;}const target=cleanPath(destination);const existing=trail.findIndex(c=>c.path===target);const next=existing>=0?trail.slice(0,existing):[...trail,{path:cleanPath(current),title:document.querySelector('h1')?.textContent?.trim().slice(0,90)||'Vibe Guide'}];a.href=withTrail(target,next,location.origin);},true);
}
