/** Keep the original project in place; additional projects use isolated namespaces. */
const activeKey='vibe-guide-active-project';
const registryKey='vibe-guide-projects';
export function activeProject(){return window.localStorage.getItem(activeKey)||'default';}
function scoped(key:string){const id=activeProject();return id==='default'?key:`vibe-project:${id}:${key}`;}
export const projectStorage={getItem:(key:string)=>window.localStorage.getItem(scoped(key)),setItem:(key:string,value:string)=>window.localStorage.setItem(scoped(key),value),removeItem:(key:string)=>window.localStorage.removeItem(scoped(key))};
export function projectList():{id:string;name:string}[]{try{const list=JSON.parse(window.localStorage.getItem(registryKey)||'[]');if(Array.isArray(list)&&list.every(p=>typeof p.id==='string'&&typeof p.name==='string'))return [{id:'default',name:'原有项目 / Original project'},...list.filter(p=>p.id!=='default')];}catch{}return [{id:'default',name:'原有项目 / Original project'}];}
export function createProject(name:string){if(!name.trim())throw Error('name');const id=crypto.randomUUID();window.localStorage.setItem(registryKey,JSON.stringify([...projectList().filter(p=>p.id!=='default'),{id,name:name.trim()}]));window.localStorage.setItem(activeKey,id);return id;}
export function switchProject(id:string){if(!projectList().some(p=>p.id===id))throw Error('project');window.localStorage.setItem(activeKey,id);}
export function exportProject(){const prefix=activeProject()==='default'?'':`vibe-project:${activeProject()}:`;const entries:Record<string,string>={};for(let i=0;i<window.localStorage.length;i++){const key=window.localStorage.key(i)!;if(prefix&&!key.startsWith(prefix))continue;const plain=prefix?key.slice(prefix.length):key;if(!plain.startsWith('vibe-')||plain.startsWith('vibe-project:')||[activeKey,registryKey].includes(plain))continue;entries[plain]=window.localStorage.getItem(key)!;}return {format:'vibe-project-backup',version:1,name:projectList().find(p=>p.id===activeProject())?.name,exportedAt:new Date().toISOString(),entries};}
export function validateBackup(value:unknown):{name:string;entries:Record<string,string>}{const b=value as ReturnType<typeof exportProject>;if(!b||b.format!=='vibe-project-backup'||b.version!==1||!b.entries||typeof b.entries!=='object'||Array.isArray(b.entries))throw Error('format');const entries=Object.entries(b.entries);if(entries.length>1500||entries.some(([key,value])=>!key.startsWith('vibe-')||key.startsWith('vibe-project:')||[activeKey,registryKey].includes(key)||typeof value!=='string'||value.length>2000000))throw Error('content');return {name:typeof b.name==='string'?b.name:'恢复的项目',entries:Object.fromEntries(entries)};}
export function restoreProject(value:unknown){const b=validateBackup(value);const old=activeProject();const id=crypto.randomUUID();try{for(const [key,value] of Object.entries(b.entries))window.localStorage.setItem(`vibe-project:${id}:${key}`,value);window.localStorage.setItem(registryKey,JSON.stringify([...projectList().filter(p=>p.id!=='default'),{id,name:`${b.name} · 恢复 / Restored`} ]));window.localStorage.setItem(activeKey,id);}catch(error){window.localStorage.setItem(activeKey,old);throw error;}}
export function readConfirmed(id:string,lang=document.documentElement.lang):string{try{const data=JSON.parse(projectStorage.getItem(`vibe-template-v1:${lang.toLowerCase()==='zh-cn'?'zh-CN':lang}:${id}`)||'null');return typeof data?.confirmed==='string'?data.confirmed:'';}catch{return '';}}

export function ideaFields(text:string):string[]{
 const lines=text.split(/\r?\n/);const values=['','','',''];let current=-1;
 for(const line of lines){const label=line.split(/[:：]/)[0].trim();const index=/^(这个项目主要给谁使用|Who will use)/i.test(label)?0:/^(这个项目要帮他们解决什么问题|What problem|Problem to solve)/i.test(label)?1:/^(项目做完后，怎样才算达到预期|How will you decide|How to test)/i.test(label)?2:/^(是否计划第二阶段开发|Will there be a second|Second phase)/i.test(label)?3:-1;if(index>=0){current=index;values[index]=line.replace(/^[^:：]+[:：]\s*/,'').trim();}else if(current>=0&&line.trim())values[current]+='\n'+line.trim();}
 return values;
}
