export function validateTemplate(value:string):string {if(!value.trim())throw new Error('empty');return value.trim();}
export function initTemplates(){const en=document.documentElement.lang==='en';document.querySelectorAll<HTMLElement>('.prompt-template').forEach(root=>{
 const editor=root.querySelector<HTMLTextAreaElement>('[data-template-editor]');if(!editor)return;
 const confirm=root.querySelector<HTMLButtonElement>('[data-confirm-template]')!;const id=editor.dataset.templateEditor!;const code=root.querySelector<HTMLElement>('[data-template-text]')!;const copy=root.querySelector<HTMLButtonElement>('[data-copy-template]')!;const output=root.querySelector<HTMLElement>('[data-template-result]')!;const status=root.querySelector<HTMLElement>('[data-template-status]')!;const saved=root.querySelector<HTMLElement>('[data-template-save]')!;const key=`vibe-template-v1:${document.documentElement.lang}:${id}`;let confirmed='';let ownChange=false;let canSave=true;let restored=false;
 const invalidate=()=>{confirmed='';copy.disabled=true;output.hidden=true;status.textContent='';};
 try{const raw=localStorage.getItem(key);if(raw){const data=JSON.parse(raw);if(typeof data.draft!=='string')throw Error();editor.value=data.draft;restored=true;saved.textContent=en?'Draft restored. Review and confirm before copying.':'已恢复草稿，核对并确认后即可复制。';}}catch{canSave=false;saved.textContent=en?'Saved draft could not be read; original data is preserved. Keep a manual copy.':'旧草稿无法读取，原记录未覆盖。请手动留底。';}
 if(!restored){editor.value=code.textContent??editor.value;if(root.dataset.templateKind!=='file'){try{const project=JSON.parse(localStorage.getItem('vibe-guide-learning-v1')||'null');if(typeof project?.idea==='string'&&project.idea.trim()&&!editor.value.includes(project.idea)){editor.value=(en?'My project idea: ':'我的项目想法：')+project.idea+'\n\n'+editor.value;}}catch{}}}
 const persist=()=>{if(!canSave)return;try{localStorage.setItem(key,JSON.stringify({draft:editor.value}));saved.textContent=en?'Draft saved in this browser. Confirm to prepare a copy.':'草稿已保存到当前浏览器。确认后生成可复制内容。';}catch{saved.textContent=en?'Saving failed. Keep the text before leaving.':'保存失败，离开前请保留当前文字。';}};
 editor.addEventListener('input',()=>{invalidate();persist();});
 const accept=(text:string)=>{confirm.disabled=false;editor.value=text;confirmed=text;ownChange=true;code.textContent=text;copy.disabled=false;output.hidden=false;status.textContent=en?'Ready to copy.':'已生成，可以复制。';persist();};
 confirm.addEventListener('click',()=>{try{accept(validateTemplate(editor.value));}catch{invalidate();saved.textContent=en?'Fill the template before confirming.':'请先填写模板，再确认生成。';editor.focus();}});
 // Existing generators provide their confirmed form values; edits invalidate that confirmation.
 root.addEventListener('template:ready',()=>accept(code.textContent!.trim()));
 root.addEventListener('template:dirty',()=>{confirm.disabled=true;invalidate();saved.textContent=en?'Source material changed. Generate again.':'填写材料已修改，请重新生成。';});
 new MutationObserver(()=>{if(ownChange){ownChange=false;return;}if(code.textContent===confirmed)return;editor.value=code.textContent??'';invalidate();}).observe(code,{childList:true,characterData:true,subtree:true});
 copy.addEventListener('click',async()=>{if(copy.disabled||!confirmed)return;status.textContent=en?'Copying…':'正在复制…';let timer:ReturnType<typeof setTimeout>|undefined;try{await Promise.race([navigator.clipboard.writeText(confirmed),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error()),1800);})]);status.textContent=en?'Copied.':'已复制。';}catch{const range=document.createRange();range.selectNodeContents(code);const selection=getSelection();selection?.removeAllRanges();selection?.addRange(range);status.textContent=en?'Text selected. Press Ctrl+C / ⌘C to copy.':'已选中文字，请按 Ctrl+C / ⌘C 复制。';}finally{if(timer)clearTimeout(timer);}});
 });}
